# This is a basic workflow to help you get started with Actions

name: 最小CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-xiong
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
      - name: 检出代码
        uses: http://192.168.105.4:3000/xqt1234/checkout.git@v4

      - name: 安装依赖
        run: sudo apt-get install -y cmake g++ ccache libgtest-dev clang-format valgrind clang-tidy

      - name: 缓存 ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('**/*.cpp', '**/*.hpp', '**/CMakeLists.txt') }}
          restore-keys: |
            ccache-${{ runner.os }}-

      - name: 编译
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build build -j$(nproc)

      - name: 运行测试
        run: build/bin/tests.bin --gtest_output=xml:test_results_${{ matrix.build-type }}.xml
      - name: 内存泄漏检查
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./bin/tests.bin
      - name: 代码格式检查
        run: |
           find include tests -name "*.hpp" -o -name "*.cpp" | xargs clang-format --dry-run -n --Werror
           echo "检查完成"
      - name: 静态分析
        run: |
          find include tests \( -name "*.cpp" -o -name "*.hpp" \) | xargs -I {} clang-tidy \
          --config-file=.clang-tidy \
          {} \
          -- -Iinclude -std=c++20